public enum EmojiList {
    public enum Animals {}
    public enum Classic {}
    public enum Clothing {}
    public enum CountryFlags {}
    public enum Faces {}
    public enum Foods {}
    public enum Household {}
    public enum Plants {}
    public enum Pure {}
    public enum SkinTones1 {}
    public enum SkinTones2 {}
    public enum SkinTones3 {}
    public enum SkinTones4 {}
    public enum SkinTones5 {}
    public enum Sports {}
    public enum Transports {}
    public enum Weather {}
}
